# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='like',
            field=models.ManyToManyField(related_name='like', to='events.Person', verbose_name=b'\xe3\x81\x84\xe3\x81\x84\xe3\x81\xad'),
        ),
    ]
