# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersolUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('mail_address', models.EmailField(max_length=75)),
                ('Self_introduction_text', models.CharField(max_length=200)),
            ],
        ),
    ]
