# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 03:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('persol_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persoluser',
            name='data',
            field=models.ImageField(default=datetime.datetime(2017, 9, 17, 3, 58, 59, 773988, tzinfo=utc), upload_to='image'),
            preserve_default=False,
        ),
    ]
