# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persol_users', '0002_persoluser_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persoluser',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='persoluser',
            old_name='Self_introduction_text',
            new_name='self_introduction_text',
        ),
        migrations.RenameField(
            model_name='persoluser',
            old_name='Surname',
            new_name='surname',
        ),
    ]
